/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package WILD;

import WILD.Clases.Arbol;
import WILD.Main.Parcial2;
import java.awt.Image;
import java.net.URL;
import java.text.Normalizer;
import javax.swing.ImageIcon;

/**
 *
 * @author Nicolino Uchiha
 */
public class Correcto extends javax.swing.JFrame {

    private final Arbol adivinador;

    /**
     * Creates new form Preguntas
     */
    public Correcto() {
        this("RESPUESTA", Parcial2.crearAdivinador());
    }

    public Correcto(String animal, Arbol adivinador) {
        this.adivinador = adivinador;
        initComponents();
        txtrespuesta.setText(animal);
        cargarImagenAnimal(animal);
        btnsi.setText("OTRA");
        btnno.setText("MENU");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnsalir = new javax.swing.JButton();
        txtlogo = new javax.swing.JLabel();
        btnno = new javax.swing.JButton();
        btnsi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtrespuesta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblrespuesta = new javax.swing.JLabel();
        txtfondo = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsalir.setBackground(new java.awt.Color(46, 94, 62));
        btnsalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/Salir.png"))); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, 300, 60));

        txtlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/Logo (1).png"))); // NOI18N
        jPanel1.add(txtlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -20, -1, 270));

        btnno.setBackground(new java.awt.Color(217, 83, 79));
        btnno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnno.setForeground(new java.awt.Color(255, 255, 255));
        btnno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/No.png"))); // NOI18N
        btnno.setText("NO");
        btnno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 120, 50));

        btnsi.setBackground(new java.awt.Color(139, 195, 74));
        btnsi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsi.setForeground(new java.awt.Color(255, 255, 255));
        btnsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/SI.png"))); // NOI18N
        btnsi.setText("SI");
        btnsi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiActionPerformed(evt);
            }
        });
        jPanel1.add(btnsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 120, 50));

//        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/Leon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        txtrespuesta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtrespuesta.setForeground(new java.awt.Color(255, 255, 255));
        txtrespuesta.setText("RESPUESTA ");
        jPanel1.add(txtrespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, -1, -1));

        jPanel2.setBackground(new java.awt.Color(27, 102, 51));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

//        lblrespuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/mosca.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblrespuesta)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblrespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 180, 170));

        txtfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/Fondo.png"))); // NOI18N
        txtfondo.setAutoscrolls(true);
        jPanel1.add(txtfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnoActionPerformed
        new JUGAR().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnnoActionPerformed

    private void btnsiActionPerformed(java.awt.event.ActionEvent evt) {
        new Preguntas(adivinador).setVisible(true);
        dispose();
    }

    private void cargarImagenAnimal(String animal) {
        URL recurso = buscarImagenAnimal(animal);
        if (recurso == null) {
            recurso = getClass().getResource("/WILD/ASSETS/Animal.png");
        }

        if (recurso == null) {
            lblrespuesta.setIcon(null);
            return;
        }

        ImageIcon icono = new ImageIcon(recurso);
        Image imagen = icono.getImage().getScaledInstance(170, 156, Image.SCALE_SMOOTH);
        lblrespuesta.setIcon(new ImageIcon(imagen));
    }

    private URL buscarImagenAnimal(String animal) {
        String[] nombres = {
            animal.trim(),
            animal.toLowerCase().trim(),
            normalizarNombreArchivo(animal)
        };
        String[] extensiones = {".jpg", ".png"};

        for (String nombre : nombres) {
            for (String extension : extensiones) {
                URL recurso = getClass().getResource("/WILD/ASSETS/" + nombre + extension);
                if (recurso != null) {
                    return recurso;
                }
            }
        }

        return null;
    }

    private String normalizarNombreArchivo(String texto) {
        String normalizado = Normalizer.normalize(texto, Normalizer.Form.NFD);
        normalizado = normalizado.replaceAll("\\p{M}", "");
        return normalizado.toLowerCase().trim();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnno;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblrespuesta;
    private javax.swing.JLabel txtfondo;
    private javax.swing.JLabel txtlogo;
    private javax.swing.JLabel txtrespuesta;
    // End of variables declaration//GEN-END:variables
}
