/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package WILD;

import WILD.Clases.Arbol;
import WILD.Main.Parcial2;

/**
 *
 * @author Nicolino Uchiha
 */
public class JUGAR extends javax.swing.JFrame {

    private final Arbol adivinador;

    /**
     * Creates new form JUGAR
     */
    public JUGAR() {
        adivinador = Parcial2.crearAdivinador();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btncomenzar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        txtlogo = new javax.swing.JLabel();
        txtanimal = new javax.swing.JLabel();
        txtfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncomenzar.setBackground(new java.awt.Color(139, 195, 74));
        btncomenzar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncomenzar.setForeground(new java.awt.Color(255, 255, 255));
        btncomenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/Pata (2).png"))); // NOI18N
        btncomenzar.setText("COMENZAR");
        btncomenzar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncomenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomenzarActionPerformed(evt);
            }
        });
        jPanel1.add(btncomenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 180, 70));

        btnsalir.setBackground(new java.awt.Color(46, 94, 62));
        btnsalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/Salir.png"))); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 180, 70));

        txtlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/Logo (1).png"))); // NOI18N
        jPanel1.add(txtlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -10, -1, -1));

        txtanimal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtanimal.setForeground(new java.awt.Color(30, 61, 47));
        txtanimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/animaltex.png"))); // NOI18N
        jPanel1.add(txtanimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 280, 100));

        txtfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/Fondo.png"))); // NOI18N
        txtfondo.setAutoscrolls(true);
        jPanel1.add(txtfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btncomenzarActionPerformed(java.awt.event.ActionEvent evt) {
        iniciarJuego();
    }

    private void iniciarJuego() {
        new Preguntas(adivinador).setVisible(true);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JUGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JUGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JUGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JUGAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JUGAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncomenzar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtanimal;
    private javax.swing.JLabel txtfondo;
    private javax.swing.JLabel txtlogo;
    // End of variables declaration//GEN-END:variables
}
