/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package WILD;

/**
 *
 * @author Nicolino Uchiha
 */
public class Preguntas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Preguntas
     */
    public Preguntas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnsalir = new javax.swing.JButton();
        txtlogo = new javax.swing.JLabel();
        btnno = new javax.swing.JButton();
        btnsi = new javax.swing.JButton();
        txtpregunta = new javax.swing.JLabel();
        jpfondotex = new javax.swing.JPanel();
        txtfondo = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsalir.setBackground(new java.awt.Color(46, 94, 62));
        btnsalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/Salir.png"))); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 300, 60));

        txtlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/Logo (1).png"))); // NOI18N
        jPanel1.add(txtlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 270));

        btnno.setBackground(new java.awt.Color(217, 83, 79));
        btnno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnno.setForeground(new java.awt.Color(255, 255, 255));
        btnno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/No.png"))); // NOI18N
        btnno.setText("NO");
        btnno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 120, 50));

        btnsi.setBackground(new java.awt.Color(139, 195, 74));
        btnsi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsi.setForeground(new java.awt.Color(255, 255, 255));
        btnsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/SI.png"))); // NOI18N
        btnsi.setText("SI");
        btnsi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 120, 50));

        txtpregunta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpregunta.setForeground(new java.awt.Color(255, 255, 255));
        txtpregunta.setText("TEXTO CAMBIANDO SEGUN LA PREGUNTA");
        jPanel1.add(txtpregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jpfondotex.setBackground(new java.awt.Color(27, 102, 51));
        jpfondotex.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jpfondotex.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jpfondotex, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 340, 160));

        txtfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WILD/ASSETS/Fondo.png"))); // NOI18N
        txtfondo.setAutoscrolls(true);
        jPanel1.add(txtfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnno;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnsi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpfondotex;
    private javax.swing.JLabel txtfondo;
    private javax.swing.JLabel txtlogo;
    private javax.swing.JLabel txtpregunta;
    // End of variables declaration//GEN-END:variables
}
